#!/usr/bin/env python3
"""Build a navigable CyberDatabase index from the mirrored HackTricks SUMMARY.md.

The script does not modify upstream source material. It creates a CyberDatabase-owned
navigation file that points back into references/hacktricks-upstream/src/.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / "references" / "hacktricks-upstream" / "src" / "SUMMARY.md"
OUTPUT = ROOT / "knowledge-base" / "hacktricks-derived" / "UPSTREAM_INDEX.md"
MIRROR_PREFIX = "../../references/hacktricks-upstream/src/"

LINK_RE = re.compile(r"^(?P<indent>\s*)-\s+\[(?P<title>[^]]+)\]\((?P<target>[^)]*)\)\s*$")
HEADING_RE = re.compile(r"^(?P<hashes>#{1,6})\s+(?P<title>.+?)\s*$")


def local_target(target: str) -> str | None:
    target = target.strip()
    if not target or target.startswith(("http://", "https://", "mailto:", "#")):
        return None
    return MIRROR_PREFIX + target


def main() -> None:
    if not SUMMARY.exists():
        raise SystemExit(f"HackTricks SUMMARY not found: {SUMMARY}")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines = SUMMARY.read_text(encoding="utf-8", errors="replace").splitlines()

    out = [
        "# HackTricks Upstream Index",
        "",
        "Generated by `scripts/build_hacktricks_index.py` from the synchronized HackTricks `src/SUMMARY.md`.",
        "",
        "This file is navigation only. The complete synchronized upstream source remains under `references/hacktricks-upstream/`, with its original notices and license information preserved.",
        "",
        "CyberDatabase-authored explanations and field guides live elsewhere under `knowledge-base/`.",
        "",
    ]

    entries = 0
    for line in lines:
        heading = HEADING_RE.match(line)
        if heading:
            level = min(len(heading.group("hashes")) + 1, 6)
            out.append(f"{'#' * level} {heading.group('title')}")
            out.append("")
            continue

        item = LINK_RE.match(line)
        if not item:
            continue

        target = local_target(item.group("target"))
        if not target:
            continue

        indent = item.group("indent")
        title = item.group("title")
        out.append(f"{indent}- [{title}]({target})")
        entries += 1

    out.extend([
        "",
        "---",
        "",
        f"Indexed entries: **{entries}**",
        "",
        "Upstream project: https://github.com/HackTricks-wiki/hacktricks",
        "",
    ])

    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {OUTPUT} with {entries} entries")


if __name__ == "__main__":
    main()
